services:
  app:
    build:
      context: ../code
      dockerfile: ../docker/php/Dockerfile
    container_name: app
    ports:
      - "5173:5173"
    volumes:
      - ../code:/var/www
    networks:
      - devtrove

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ../code:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - devtrove

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: devtrove
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - devtrove

  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    container_name: rabbitmq
    environment:
      DOMAIN_NAME: rabbitmq.localhost
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit123.
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - devtrove

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    environment:
      DOMAIN_NAME: mailhog.localhost
    ports:
      - '1025:1025'
      - '1080:1080'
      - '8025:8025'
    networks:
      - devtrove  

networks:
  devtrove:
